#! /bin/bash
alias "set-brightness"='xrandr --output eDP1 --brightness $1'
alias ls='ls -F --color=auto --group-directories-first'
alias lla='ls -la'
alias la='ls -la'

function _update_ps1(){
        export PS1="$(~/.powerline-shell/powerline-shell.py $? 2> /dev/null)"
}

export PROMPT_COMMAND="_update_ps1; $PROMPT_COMMAND"